version: '3'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: db
    ports:
      - 8081:80  # เปลี่ยนจาก 8080 เป็น 8081
    depends_on:
      - db

volumes:
  db_data: